name: Dry-run Renovate
description: 'Dry-run Renovate and output to summary'

inputs:
  cache:
    description: 'if `true`, cache ~/.npm'
    required: false
    default: "true"
  log-level:
    description: 'Renovate log level [trace|debug|info|warn|error|fatal]'
    required: false
    default: "debug"
  log-format:
    description: 'Renovate log format [text|json]'
    required: false
    default: "text"
  config-file:
    description: 'Renovate config file'
    required: true
  save-log:
    description: 'if `true`, save log file'
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup
      id: setup
      shell: bash
      run: |
        # Get latest renovate major version
        echo "renovate-version=$(npm show renovate version --no-update-notifier | cut -d . -f 1)" >> $GITHUB_OUTPUT
        echo "renovate-log=${{ runner.temp }}/renovate-dry-run.log" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      if: inputs.cache == 'true'
      with:
        path: ~/.npm
        key: npm-renovate-major-v${{ steps.setup.outputs.renovate-version }}

    - name: Dry run renovate
      env:
        # Use `GitHub Action` user to make it explicit that the execution is by github actions.
        # ref: https://github.com/actions/checkout/issues/13
        RENOVATE_USERNAME: GitHub Action
        RENOVATE_GIT_AUTHOR: GitHub Action <action@github.com>
        RENOVATE_TOKEN: ${{ github.token }}
        LOG_LEVEL: ${{ inputs.log-level }}
        LOG_FORMAT: ${{ inputs.log-format }}
        RENOVATE_CONFIG_FILE: ${{ inputs.config-file }}
        DRY_RUN_LOG_FILE_NAME: renovate-dry-run.log
      shell: bash
      run: |
        npx renovate --schedule= --require-config=ignored --dry-run ${{ github.repository }} \
          | tee ${{ steps.setup.outputs.renovate-log }}

    - name: Output to step summary
      if: always()
      shell: bash
      run: |
        # output to step summary
        echo "# Renovate dry run log" >> $GITHUB_STEP_SUMMARY
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>detail</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```json' >> $GITHUB_STEP_SUMMARY
        cat ${{ steps.setup.outputs.renovate-log }} >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY

    - name: Save log
      if: always() && inputs.save-log == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: renovate-dry-run-log
        path: |
          ${{ steps.setup.outputs.renovate-log }}
