name: Dry-run Renovate

on:
  push:
    paths:
      - .github/workflows/dry-run-renovate.yaml
      - renovate.json5
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json5
