name: Release
run-name: Release ${{ inputs.version }}

permissions:
  # Required for tag push and release creation
  # https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#contents
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Tagging version (ex: v1.0.1)"
        required: true
      isMajorVersion:
        type: boolean
        description: If true, it will update the MAJOR version of the tag.
        default: true
      isRelease:
        type: boolean
        description: If true, it will create a GitHub Release
        default: true

jobs:
  call:
    # https://github.com/korosuke613/actions
    uses: korosuke613/actions/.github/workflows/tagging.yaml@ac3df9b1bc31f162ed0445087b925eddca39ab05
    with:
      version: ${{ inputs.version }}
      isMajorVersion: ${{ inputs.isMajorVersion }}
      isRelease: ${{ inputs.isRelease }}
