name: Test action

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  normal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json

  no-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json
          cache: false

  log-level:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json
          log-level: info

  log-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json
          log-format: json

  save-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json
          save-log: true

  detail-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config-file: renovate.json
          log-level: info  # To reduce page occupancy.
          detail-summary: false
